apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
        log stdout format raw local0
        maxconn 2000

    defaults
        mode tcp
        timeout connect 5s
        timeout client  1m
        timeout server  1m

    frontend postgres_front
        bind *:5432
        default_backend postgres_back

    backend postgres_back
        mode tcp
        option tcp-check
        balance roundrobin
        server patroni-0 patroni-0.patroni:5432 check inter 2000 rise 2 fall 3
        server patroni-1 patroni-1.patroni:5432 check inter 2000 rise 2 fall 3
        server patroni-2 patroni-2.patroni:5432 check inter 2000 rise 2 fall 3
