apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-stack
  namespace: nexusnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-stack
  template:
    metadata:
      labels:
        app: monitoring-stack
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.54.1
          ports:
            - containerPort: 9090
        - name: grafana
          image: grafana/grafana:11.1.4
          ports:
            - containerPort: 3000
