apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: nexusnet
spec:
  selector:
    app: monitoring-stack
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
    - name: grafana
      port: 3000
      targetPort: 3000
