apiVersion: v1
kind: Service
metadata:
  name: nexusnet-api
  labels:
    app: nexusnet-api
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nexusnet-api
